[book]
authors = ["Salif Mehmed"]
language = "bg"
multilingual = false
src = "src"
title = "Граматика на глобаса"
description = "Български превод на граматиката на глобаса."

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
smart-punctuation = false
git-repository-url = "https://github.com/salif/gramati-fe-globasa"
edit-url-template = "https://github.com/salif/gramati-fe-globasa/edit/main/claude/{path}"
site-url = "/claude/"
