[book]
authors = ["Salif Mehmed"]
language = "ru"
multilingual = false
src = "src"
title = "Грамматика глобаса"
description = "Русский перевод грамматики языка глобаса, выполненный с использованием языковой модели Джемини"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/custom.css"]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/ru-gemini/{path}"
site-url = "/gramati-fe-globasa/ru-gemini/"

[output.epub]
use-default-css = true
no-section-label = false
curly-quotes = false
