[book]
authors = ["The Globasa Team", "Salif Mehmed"]
language = "en"
multilingual = false
src = "src"
title = "Complete Globasa Grammar"
description = "A copy of the Complete Globasa Grammar and the source for the translated books"

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/eng/{path}"
site-url = "/gramati-fe-globasa/eng/"

[output.epub]
use-default-css = true
no-section-label = false
curly-quotes = false

# [output.pdf]
# theme = "light"
# paper-width = 8.3
# paper-height = 11.7
# margin-top = 0.4
# margin-bottom = 0.4
# margin-left = 0.4
# margin-right = 0.4
# display-header-footer = false
# print-background = false

[output.ze]
command = "just build-ze Gramati_fe_Globasa_Mesi_09_2024_eng build-ze-ignore"
