[book]
authors = ["Salif Mehmed"]
language = "zh"
multilingual = false
src = "src"
title = "格洛巴萨语法"
description = "格洛巴萨（Globasa）这一人造语言的语法的非官方中文译本"

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/zh-gemini/{path}"
site-url = "/gramati-fe-globasa/zh-gemini/"

[output.epub]
cover-image = "cover.png"
curly-quotes = false
