[book]
authors = ["Salif Mehmed"]
language = "id"
multilingual = false
src = "src"
title = "Tata Bahasa Globasa"
description = "Terjemahan tidak resmi tata bahasa dari bahasa buatan bernama Globasa ke dalam Bahasa Indonesia. Sebagian dari terjemahan ini dibuat menggunakan model bahasa Gemini."

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/id-gemini/{path}"
site-url = "/gramati-fe-globasa/id-gemini/"

[output.epub]
use-default-css = true
no-section-label = false
curly-quotes = false
