[book]
authors = ["the Globasa Team", "Salif Mehmed"]
language = "en"
multilingual = false
src = "src"
title = "Complete Globasa Grammar"
description = "A copy of the Complete Globasa Grammar and the source for the translated books"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/custom.css"]
default-theme = "rust"
preferred-dark-theme = "mocha"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/eng/{path}"
site-url = "/eng/"
