[book]
authors = ["Salif Mehmed"]
language = "pt"
multilingual = false
src = "src"
title = "Gramática da globasa"
description = "Tradução não oficial para o português da gramática da língua construída chamada globasa"

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/pt-gemini/{path}"
site-url = "/gramati-fe-globasa/pt-gemini/"

[output.epub]
cover-image = "cover.png"
curly-quotes = false
