[book]
authors = ["Salif Mehmed"]
language = "tr"
multilingual = false
src = "src"
title = "Globasa dilbilgisi"
description = "Globasa adı verilen yapay dilin gramerinin resmi olmayan Türkçe çevirisi. Çevirinin bazı kısımları Gemini dil modeli kullanılarak yapılmıştır."

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/tr-gemini/{path}"
site-url = "/gramati-fe-globasa/tr-gemini/"

[output.epub]
curly-quotes = false
