[book]
authors = ["Salif Mehmed"]
language = "tr"
multilingual = false
src = "src"
title = "Globasa dilbilgisi"
description = "Globasa dilbilgisinin Türkçe çevirisi (Google Gemini ile)"

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/tr-gemini/{path}"
site-url = "/gramati-fe-globasa/tr-gemini/"

[output.epub]
use-default-css = true
no-section-label = false
curly-quotes = false

[output.ze]
command = "just build-ze Gramati_fe_Globasa_Mesi_08_2024_tr_gemini build-ze-ignore"
