plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

title: "Gramati fe Globasa"
description: "Kompleto Gramati fe Globasa"
baseurl: "/gramati-fe-globasa"
repository: "salif/gramati-fe-globasa"
lang: glb

author:
  name: "Salif Mehmed"
  url: "https://salif.eu"

social:
  name: "Globasa-Xwexi"
  links:
    - https://bsky.app/profile/globasa.salif.eu
