plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: "Gramati fe Globasa"
description: "kitabu"
baseurl: "/gramati-fe-globasa"
repository: "salif/gramati-fe-globasa"

author:
  name: "Salif Mehmed"
  url: "https://salif.eu"
