[book]
authors = ["Salif Mehmed"]
language = "ja"
multilingual = false
src = "src"
title = "グロバサ文法"
description = "グロバサ (Globasa) と呼ばれる人工言語の文法の非公式日本語訳"

[output.html]
default-theme = "rust-sans"
preferred-dark-theme = "mocha-sans"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/ja-gemini/{path}"
site-url = "/gramati-fe-globasa/ja-gemini/"

[output.epub]
cover-image = "cover.png"
curly-quotes = false
