[book]
authors = ["Salif Mehmed"]
language = "fa"
text-direction = "rtl"
multilingual = false
src = "src"
title = "دستور زبان گلوباسا"
description = ""

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/fa-gemini/{path}"
site-url = "/gramati-fe-globasa/fa-gemini/"

[output.epub]
cover-image = "cover.png"
curly-quotes = false
