[book]
authors = ["Salif Mehmed"]
language = "bg"
multilingual = false
src = "src"
title = "Граматика на глобаса"
description = "Неофициален български превод на граматиката на конструирания език глобаса (Globasa). Части от превода са направени с помощта на езиковия модел Джемини."

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/bg-gemini/{path}"
site-url = "/gramati-fe-globasa/bg-gemini/"

[output.epub]
curly-quotes = false
