[book]
authors = ["Salif Mehmed"]
language = "eo"
multilingual = false
src = "src"
title = "Gramatiko de Globasa"
description = "Neoficiala Esperanta traduko de la gramatiko de la konstruita lingvo nomata Globasa"

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/eo-gemini/{path}"
site-url = "/gramati-fe-globasa/eo-gemini/"

[output.epub]
cover-image = "cover.png"
curly-quotes = false
