[book]
authors = ["Salif Mehmed"]
language = "de"
multilingual = false
src = "src"
title = "Globasa Grammatik"
description = "Eine inoffizielle deutsche Übersetzung der Grammatik der konstruierten Sprache namens Globasa. Teile der Übersetzung wurden mit dem Gemini-Sprachmodell erstellt."

[output.html]
default-theme = "rust-clr"
preferred-dark-theme = "mocha-clr"
smart-punctuation = false
git-repository-url = "https://codeberg.org/salif/gramati-fe-globasa"
edit-url-template = "https://codeberg.org/salif/gramati-fe-globasa/_edit/main/books/de-gemini/{path}"
site-url = "/gramati-fe-globasa/de-gemini/"

[output.epub]
use-default-css = false
no-section-label = false
curly-quotes = false
